---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2025-06-09T23:05:56.047410537+04:00"
  name: instavote
  namespace: instavote
spec:
  interval: 1h
  ref:
    branch: main
  timeout: 1m0s
  secretRef:
    name: github-instavote
  url: https://github.com/Evardanyan/instavote-deploy.git
