apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-helmrelease.yaml
- db-helmrepository.yaml
- github-instavote.yaml
- instavote-gitrepository.yaml
- instavote-receiver.yaml
- redis-staging-alert.yaml
- redis-staging-kustomization.yaml
- result-helmrelease.yaml
- result-imagepolicy.yaml
- result-imagerepository.yaml
- result-imageupdateautomation.yaml
- slack-notify-alert.yaml
- slack-provider.yaml
- vote-imagepolicy.yaml
- vote-imagerepository.yaml
- vote-imageupdateautomation.yaml
- vote-staging-alert.yaml
- vote-staging-kustomization.yaml
