---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2025-06-23T22:49:17.424116311+04:00"
  name: instavote-all
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: instavote
  update:
    path: ./deploy/vote/staging
    strategy: Setters
